services:
  webpanel:
    image: webpanel
    build:
      context: .
      dockerfile: ./Dockerfile.optimized
    env_file:
      - ENV_DOCKER.txt
    environment:
      BACKEND_URL: "http://127.0.0.1:8000"
      NEXT_PUBLIC_API_URL: ""
    ports:
      - "3000:3000"
      - "8000:8000"
    restart: unless-stopped
